export interface Repository extends Object  {
	id: number;
	node_id: string;
	name: string;
	full_name: string;
	private: boolean;
	owner: Owner;
	html_url: string;
	description: string;
	fork: boolean;
	url: string;
	forks_url: string;
	keys_url: string;
	collaborators_url: string;
	teams_url: string;
	hooks_url: string;
	issue_events_url: string;
	events_url: string;
	assignees_url: string;
	branches_url: string;
	tags_url: string;
	blobs_url: string;
	git_tags_url: string;
	git_refs_url: string;
	trees_url: string;
	statuses_url: string;
	languages_url: string;
	stargazers_url: string;
	contributors_url: string;
	subscribers_url: string;
	subscription_url: string;
	commits_url: string;
	git_commits_url: string;
	comments_url: string;
	issue_comment_url: string;
	contents_url: string;
	compare_url: string;
	merges_url: string;
	archive_url: string;
	downloads_url: string;
	issues_url: string;
	pulls_url: string;
	milestones_url: string;
	notifications_url: string;
	labels_url: string;
	releases_url: string;
	deployments_url: string;
	created_at: Date;
	updated_at: Date;
	pushed_at: Date;
	git_url: string;
	ssh_url: string;
	clone_url: string;
	svn_url: string;
	homepage: string;
	size: number;
	stargazers_count: number;
	watchers_count: number;
	language: string;
	has_issues: boolean;
	has_projects: boolean;
	has_downloads: boolean;
	has_wiki: boolean;
	has_pages: boolean;
	forks_count: number;
	mirror_url: null;
	archived: boolean;
	disabled: boolean;
	open_issues_count: number;
	license: License;
	forks: number;
	open_issues: number;
	watchers: number;
	default_branch: string;
	temp_clone_token: null;
	network_count: number;
	subscribers_count: number;
}

export interface License extends Object  {
	key: string;
	name: string;
	spdx_id: string;
	url: string;
	node_id: string;
}

export interface Owner extends Object {
	login: string;
	id: number;
	node_id: string;
	avatar_url: string;
	gravatar_id: string;
	url: string;
	html_url: string;
	followers_url: string;
	following_url: string;
	gists_url: string;
	starred_url: string;
	subscriptions_url: string;
	organizations_url: string;
	repos_url: string;
	events_url: string;
	received_events_url: string;
	type: string;
	site_admin: boolean;
}

export interface Contributors extends Owner {
	contributions: number;
}

export type Languages = {
	[key in keyof LanguagesColor]: number;
}

export interface LanguagesColor extends Object {
	'1C Enterprise'?: string;
	'4D'?: null;
	'ABAP'?: string;
	'ABAP CDS'?: string;
	'ActionScript'?: string;
	'Ada'?: string;
	'Agda'?: string;
	'AGS Script'?: string;
	'AL'?: string;
	'Alloy'?: string;
	'Alpine Abuild'?: any;
	'AMPL'?: string;
	'AngelScript'?: string;
	'ANTLR'?: string;
	'Apex'?: string;
	'API Blueprint'?: string;
	'APL'?: string;
	'Apollo Guidance Computer'?: string;
	'AppleScript'?: string;
	'Arc'?: string;
	'ASL'?: any;
	'ASP.NET'?: string;
	'AspectJ'?: string;
	'Assembly'?: string;
	'Asymptote'?: string;
	'ATS'?: string;
	'Augeas'?: any;
	'AutoHotkey'?: string;
	'AutoIt'?: string;
	'Awk'?: any;
	'Ballerina'?: string;
	'Batchfile'?: string;
	'Beef'?: string;
	'Befunge'?: any;
	'Bison'?: string;
	'BitBake'?: any;
	'Blade'?: string;
	'BlitzBasic'?: any;
	'BlitzMax'?: string;
	'Bluespec'?: any;
	'Boo'?: string;
	'Boogie'?: string;
	'Brainfuck'?: string;
	'Brightscript'?: any;
	'Browserslist'?: string;
	'C'?: string;
	'C#'?: string;
	'C++'?: string;
	'C2hs Haskell'?: any;
	'Cap\'n Proto'?: any;
	'CartoCSS'?: any;
	'Ceylon'?: string;
	'Chapel'?: string;
	'Charity'?: any;
	'ChucK'?: any;
	'Cirru'?: string;
	'Clarion'?: string;
	'Classic ASP'?: string;
	'Clean'?: string;
	'Click'?: string;
	'CLIPS'?: any;
	'Clojure'?: string;
	'Closure Templates'?: string;
	'CMake'?: any;
	'COBOL'?: any;
	'CodeQL'?: any;
	'CoffeeScript'?: string;
	'ColdFusion'?: string;
	'ColdFusion CFC'?: string;
	'Common Lisp'?: string;
	'Common Workflow Language'?: string;
	'Component Pascal'?: string;
	'Cool'?: any;
	'Coq'?: any;
	'Crystal'?: string;
	'CSON'?: string;
	'Csound'?: any;
	'Csound Document'?: any;
	'Csound Score'?: any;
	'CSS'?: string;
	'Cuda'?: string;
	'CWeb'?: any;
	'Cycript'?: any;
	'Cython'?: any;
	'D'?: string;
	'Dafny'?: string;
	'Dart'?: string;
	'DataWeave'?: string;
	'Dhall'?: string;
	'DIGITAL Command Language'?: any;
	'DM'?: string;
	'Dockerfile'?: string;
	'Dogescript'?: string;
	'DTrace'?: any;
	'Dylan'?: string;
	'E'?: string;
	'eC'?: string;
	'ECL'?: string;
	'ECLiPSe'?: any;
	'Eiffel'?: string;
	'EJS'?: string;
	'Elixir'?: string;
	'Elm'?: string;
	'Emacs Lisp'?: string;
	'EmberScript'?: string;
	'EQ'?: string;
	'Erlang'?: string;
	'F#'?: string;
	'F*'?: string;
	'Factor'?: string;
	'Fancy'?: string;
	'Fantom'?: string;
	'Faust'?: string;
	'Filebench WML'?: any;
	'Filterscript'?: any;
	'fish'?: any;
	'FLUX'?: string;
	'Forth'?: string;
	'Fortran'?: string;
	'Fortran Free Form'?: any;
	'FreeMarker'?: string;
	'Frege'?: string;
	'Futhark'?: string;
	'G-code'?: string;
	'Game Maker Language'?: string;
	'GAML'?: string;
	'GAMS'?: any;
	'GAP'?: any;
	'GCC Machine Description'?: any;
	'GDB'?: any;
	'GDScript'?: string;
	'Gemfile.lock'?: string;
	'Genie'?: string;
	'Genshi'?: any;
	'Gentoo Ebuild'?: any;
	'Gentoo Eclass'?: any;
	'Gherkin'?: string;
	'GLSL'?: any;
	'Glyph'?: string;
	'Gnuplot'?: string;
	'Go'?: string;
	'Golo'?: string;
	'Gosu'?: string;
	'Grace'?: any;
	'Grammatical Framework'?: string;
	'GraphQL'?: string;
	'Groovy'?: string;
	'Groovy Server Pages'?: any;
	'Hack'?: string;
	'Haml'?: string;
	'Handlebars'?: string;
	'Harbour'?: string;
	'Haskell'?: string;
	'Haxe'?: string;
	'HCL'?: any;
	'HiveQL'?: string;
	'HLSL'?: any;
	'HolyC'?: string;
	'HTML'?: string;
	'Hy'?: string;
	'HyPhy'?: any;
	'IDL'?: string;
	'Idris'?: string;
	'IGOR Pro'?: string;
	'ImageJ Macro'?: string;
	'Inform 7'?: any;
	'Inno Setup'?: any;
	'Io'?: string;
	'Ioke'?: string;
	'Isabelle'?: string;
	'Isabelle ROOT'?: any;
	'J'?: string;
	'Jasmin'?: any;
	'Java'?: string;
	'Java Server Pages'?: any;
	'JavaScript'?: string;
	'JavaScript+ERB'?: any;
	'JFlex'?: string;
	'Jison'?: any;
	'Jison Lex'?: any;
	'Jolie'?: string;
	'jq'?: string;
	'JSONiq'?: string;
	'Jsonnet'?: string;
	'Julia'?: string;
	'Jupyter Notebook'?: string;
	'Kaitai Struct'?: string;
	'Kotlin'?: string;
	'KRL'?: string;
	'LabVIEW'?: any;
	'Lark'?: string;
	'Lasso'?: string;
	'Latte'?: string;
	'Lean'?: any;
	'Less'?: string;
	'Lex'?: string;
	'LFE'?: string;
	'LilyPond'?: any;
	'Limbo'?: any;
	'Liquid'?: string;
	'Literate Agda'?: any;
	'Literate CoffeeScript'?: any;
	'Literate Haskell'?: any;
	'LiveScript'?: string;
	'LLVM'?: string;
	'Logos'?: any;
	'Logtalk'?: any;
	'LOLCODE'?: string;
	'LookML'?: string;
	'LoomScript'?: any;
	'LSL'?: string;
	'Lua'?: string;
	'M'?: any;
	'M4'?: any;
	'M4Sugar'?: any;
	'Macaulay2'?: string;
	'Makefile'?: string;
	'Mako'?: any;
	'Markdown'?: string;
	'Marko'?: string;
	'Mask'?: string;
	'Mathematica'?: any;
	'MATLAB'?: string;
	'Max'?: string;
	'MAXScript'?: string;
	'mcfunction'?: string;
	'Mercury'?: string;
	'Meson'?: string;
	'Metal'?: string;
	'MiniD'?: any;
	'Mirah'?: string;
	'mIRC Script'?: string;
	'MLIR'?: string;
	'Modelica'?: any;
	'Modula-2'?: any;
	'Modula-3'?: string;
	'Module Management System'?: any;
	'Monkey'?: any;
	'Moocode'?: any;
	'MoonScript'?: any;
	'Motorola 68K Assembly'?: any;
	'MQL4'?: string;
	'MQL5'?: string;
	'MTML'?: string;
	'MUF'?: any;
	'mupad'?: any;
	'Mustache'?: string;
	'Myghty'?: any;
	'NASL'?: any;
	'NCL'?: string;
	'Nearley'?: string;
	'Nemerle'?: string;
	'nesC'?: string;
	'NetLinx'?: string;
	'NetLinx+ERB'?: string;
	'NetLogo'?: string;
	'NewLisp'?: string;
	'Nextflow'?: string;
	'Nim'?: string;
	'Nit'?: string;
	'Nix'?: string;
	'NSIS'?: any;
	'Nu'?: string;
	'NumPy'?: string;
	'Nunjucks'?: string;
	'NWScript'?: string;
	'Objective-C'?: string;
	'Objective-C++'?: string;
	'Objective-J'?: string;
	'ObjectScript'?: string;
	'OCaml'?: string;
	'Odin'?: string;
	'Omgrofl'?: string;
	'ooc'?: string;
	'Opa'?: any;
	'Opal'?: string;
	'Open Policy Agent'?: any;
	'OpenCL'?: any;
	'OpenEdge ABL'?: any;
	'OpenQASM'?: string;
	'OpenRC runscript'?: any;
	'OpenSCAD'?: any;
	'Org'?: string;
	'Ox'?: any;
	'Oxygene'?: string;
	'Oz'?: string;
	'P4'?: string;
	'Pan'?: string;
	'Papyrus'?: string;
	'Parrot'?: string;
	'Parrot Assembly'?: any;
	'Parrot Internal Representation'?: any;
	'Pascal'?: string;
	'Pawn'?: string;
	'Pep8'?: string;
	'Perl'?: string;
	'PHP'?: string;
	'PicoLisp'?: any;
	'PigLatin'?: string;
	'Pike'?: string;
	'PLpgSQL'?: any;
	'PLSQL'?: string;
	'PogoScript'?: string;
	'Pony'?: any;
	'PostScript'?: string;
	'POV-Ray SDL'?: any;
	'PowerBuilder'?: string;
	'PowerShell'?: string;
	'Prisma'?: string;
	'Processing'?: string;
	'Prolog'?: string;
	'Propeller Spin'?: string;
	'Pug'?: string;
	'Puppet'?: string;
	'PureBasic'?: string;
	'PureScript'?: string;
	'Python'?: string;
	'Python console'?: any;
	'q'?: string;
	'Q#'?: string;
	'QMake'?: any;
	'QML'?: string;
	'Qt Script'?: string;
	'Quake'?: string;
	'R'?: string;
	'Racket'?: string;
	'Ragel'?: string;
	'Raku'?: string;
	'RAML'?: string;
	'Rascal'?: string;
	'REALbasic'?: any;
	'Reason'?: string;
	'Rebol'?: string;
	'Record Jar'?: string;
	'Red'?: string;
	'Redcode'?: any;
	'Ren\'Py'?: string;
	'RenderScript'?: any;
	'ReScript'?: string;
	'REXX'?: any;
	'Ring'?: string;
	'Riot'?: string;
	'RobotFramework'?: any;
	'Roff'?: string;
	'Rouge'?: string;
	'RPC'?: any;
	'Ruby'?: string;
	'RUNOFF'?: string;
	'Rust'?: string;
	'Sage'?: any;
	'SaltStack'?: string;
	'SAS'?: string;
	'Sass'?: string;
	'Scala'?: string;
	'Scaml'?: string;
	'Scheme'?: string;
	'Scilab'?: any;
	'SCSS'?: string;
	'sed'?: string;
	'Self'?: string;
	'ShaderLab'?: any;
	'Shell'?: string;
	'ShellSession'?: any;
	'Shen'?: string;
	'Sieve'?: any;
	'Slash'?: string;
	'Slice'?: string;
	'Slim'?: string;
	'Smali'?: any;
	'Smalltalk'?: string;
	'Smarty'?: any;
	'SmPL'?: string;
	'SMT'?: any;
	'Solidity'?: string;
	'SourcePawn'?: string;
	'SQF'?: string;
	'SQLPL'?: any;
	'Squirrel'?: string;
	'SRecode Template'?: string;
	'Stan'?: string;
	'Standard ML'?: string;
	'Starlark'?: string;
	'Stata'?: any;
	'Stylus'?: string;
	'SuperCollider'?: string;
	'Svelte'?: string;
	'SVG'?: string;
	'Swift'?: string;
	'SWIG'?: any;
	'SystemVerilog'?: string;
	'Tcl'?: string;
	'Tcsh'?: any;
	'Terra'?: string;
	'TeX'?: string;
	'Thrift'?: any;
	'TI Program'?: string;
	'TLA'?: any;
	'TSQL'?: any;
	'TSX'?: any;
	'Turing'?: string;
	'Twig'?: string;
	'TXL'?: any;
	'TypeScript'?: string;
	'Unified Parallel C'?: string;
	'Unix Assembly'?: any;
	'Uno'?: string;
	'UnrealScript'?: string;
	'UrWeb'?: any;
	'V'?: string;
	'Vala'?: string;
	'VBA'?: string;
	'VBScript'?: string;
	'VCL'?: string;
	'Verilog'?: string;
	'VHDL'?: string;
	'Vim script'?: string;
	'Visual Basic .NET'?: string;
	'Volt'?: string;
	'Vue'?: string;
	'wdl'?: string;
	'WebAssembly'?: string;
	'WebIDL'?: any;
	'wisp'?: string;
	'Wollok'?: string;
	'X10'?: string;
	'xBase'?: string;
	'XC'?: string;
	'Xojo'?: any;
	'XProc'?: any;
	'XQuery'?: string;
	'XS'?: any;
	'XSLT'?: string;
	'Xtend'?: any;
	'Yacc'?: string;
	'YAML'?: string;
	'YARA'?: string;
	'YASnippet'?: string;
	'ZAP'?: string;
	'Zeek'?: any;
	'ZenScript'?: string;
	'Zephir'?: string;
	'Zig'?: string;
	'ZIL'?: string;
	'Zimpl'?: any;
}
